### ISSUE TITLE
Implement add-to-module-exports

### ISSUE THREAD

**Issue by klazuka** [durkiewicz/elm-plugin#18]
# Feature Proposal
## Overview

Provide an intention to add a value/function declaration to the module's list of exports. Currently there is a lot of dancing around as you add/remove new code and want to control its visibility to other modules.
## Example

For instance, if my file looks like this:

``` elm
module Villains exposing ( madScientist )

madScientist : String
madScientist =
    "Mad Scientist"
```

And now I define another villain:

``` elm
lexLuther : String
lexLuther =
    "Lex Luther"
```

In order to add `lexLuther` to the module's `exposing` list, all I should have to do is put the cursor over `lexLuther`, press option-enter to invoke IntelliJ's intentions system, and then select an action to expose the declaration.

The end result would look like this:

``` elm
module Villains exposing
    ( madScientist
    , lexLuther
    )

madScientist : String
madScientist =
    "Mad Scientist"

lexLuther : String
lexLuther =
    "Lex Luther"
```

**Comment by durkiewicz** [comment]
I like this idea. I would even extend it:

- when a value is already exposed then there should also be an intention that makes the value private again

- I would also add [line markers](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/line_marker_provider.html) to all values so that it's clear which value is private and which is public without having to scroll up to the header of the module. We could take standard visibility icons from IntelliJ:

https://www.jetbrains.com/help/idea/2016.2/symbols.html

**Comment by klazuka** [comment]
Yep, I had both in-mind. Wanted to start small initially. But now I'm convinced that they are both necessary to "round-out" the feature so that it works as a cohesive whole. 👍

**Comment by Birowsky** [comment]
@durkiewicz is this implemented? Why are you closing it?

**Comment by durkiewicz** [comment]
@Birowsky I'm sorry, I did not realize that this issue is observed by anyone else apart from Keith - that's why I did not put any comments here (Keith knows what is going on: https://github.com/durkiewicz/elm-plugin/issues/82).
The answer is: no, it is not implemented. I'm just turning the lights off :-( I do not have enough resources to maintain the plugin.

**Comment by Birowsky** [comment]
OOoooh, right :}  I thought this thread was from his plugin :D

No worries, he's doing a great job there.
