### ISSUE TITLE
Implement add-import-statement intention

### ISSUE THREAD

**Issue by klazuka** [durkiewicz/elm-plugin#19]
# Feature Proposal

## Intention Action: Add Import Statement

When the cursor is over an unresolved reference which *could* be resolved by importing a module in the project, an intention should be provided to easily add the import.

## Details

* We should look for candidate modules in the user's source files as well as from `elm-package.json`. I think this is already handled by the plugin since we treat `elm-stuff` as a source-root.
* If the selected element is a "dotted" name (e.g. `String.length`), then just the module name should be imported (e.g. `import String`)
* If the selected element is a "bare" name (e.g. `length`), then the value's name itself should be imported (e.g. `import String exposing (length)`)

The last example, `length`, would presumably have many candidates. The user should be shown the list of candidate modules to select from.

## Related Work

* optimize imports
* convert between importing a value name in a qualified manner (`String.length`) and unqualified (`length`)
* assuming that we extend code completion to present currently-unresolvable-references, selecting such a result would add an import in a manner similar to this intention
* add-to-exports (see #18)

**Comment by durkiewicz** [comment]
It should be doable using `registerFix` method of the `AnnotationHolder`.
It will probably be necessary to extend the `ElmModuleIndex` (or create another index?) so that it's possible to get matching files by their exposed values, without knowing their module names. Otherwise, the plugin would have to scan ALL files every time there's any unresolved reference. That would probably decrease performance significantly.

**Comment by klazuka** [comment]
@durkiewicz I'm working on this currently. So far I'm getting by with the existing module index. It only needs to scan all the files when the intention is invoked, so it's manageable. But I agree that for large projects we would definitely want to be able to do this lookup more efficiently.

On the topic of large projects, when are you planning on dropping support for Elm 0.16? My workflow right now is a bit awkward since I have Elm 0.17 installed for my own projects, but then I need Elm 0.16 for test projects related to the plugin. Maybe you have a better workflow? Do you have both versions of Elm installed side-by-size?

**Comment by klazuka** [comment]
Status update: I've made some decent progress on this in [my branch](https://github.com/klazuka/elm-plugin/tree/add-import-intention)

- [x] basic qualified import (e.g. `import String`)
- [x] basic exposed import (e.g. `import String exposing (dropLeft)`)
- [x] tests 😄 
- [ ] import types
- [ ] import union type constructors
- [ ] sort the imports
- [ ] efficient symbol lookup index

**Comment by durkiewicz** [comment]
@klazuka Sorry for not replying - I've been quite busy recently. You can have 2 versions of Elm installed quite easily - Elm 0.16 works fine when it's installed as project's local NPM dependency - you can call it using `./node_modules/.bin/elm-make` inside your test project.
Elm 0.16 and 0.17 are almost the same from syntax and PSI point of view but on the other hand they are significantly different from program architecture point of view (because of lack of `Signal`s in 0.17). Large projects written in Elm 0.16 are practically unupgradable to 0.17 and that's why I would like to keep supporting Elm 0.16 as long as it doesn't cause any problems. When Elm 0.18, 0.19 or any other introduces some breaking changes from parser point of view then I'll probably drop support for older versions. But I don't find it a problem with 0.17.

**Comment by klazuka** [comment]
@durkiewicz cool. I didn't even think to try installing it locally. Anyway, your reasoning for 0.16 makes sense. Although I wonder why not do it the other way around: develop against 0.17 and backport to 0.16 when making a release?

**Comment by durkiewicz** [comment]
@klazuka That should be possible but it would require some hacking from Git point of view because `master` is ahead of `elm-0.16` branch. I would need to merge `master` to `elm-0.16` and then add some commits that reverse all the changes that has just been added by the merge. I may try to do that at some point...

**Comment by amcsi** [comment]
It's a typical git workflow to work on the "lesser" branch (e.g. 0.16), then merge into the newer version branch (e.g. 0.17)

**Comment by klazuka** [comment]
The reason I brought it up is that my own project is 0.17, and so the current branch strategy makes it difficult for me to use the plugin while developing it. So for instance, right now I'm working on this add-import feature, and I'd like to use/test it in my project.

I think most people's expectation would be that trunk/master tracks the current/stable version of Elm, with some gap shortly after a new/major Elm release. And that any compatibility with old versions would be provided by a separate branch.

In any case, it's no big deal. The current workflow is fine with me.

**Comment by klazuka** [comment]
@durkiewicz this work is now feature-complete on my branch. I will be preparing a PR shortly (I want to make another pass over the code to make sure that I'm following your code style and naming conventions).

One thing that I have *not* done is create a lookup index from exported value/type name to module. I've been testing with the source code for [Mantl UI](https://github.com/CiscoCloud/mantl-ui-frontend), and performance is nearly instant on my computer. This project has 102 `.elm` files in the project/elm-stuff. So it would seem that we could get away with the existing indexes for now. If you have a larger project to test with, I'd be interested in hearing the results.

**Comment by klazuka** [comment]
Done pending release.

**Comment by durkiewicz** [comment]
@klazuka The feature is released. I've also made `master` branch the master so you don't need to worry about Elm 0.16 anymore.
