### ISSUE TITLE
Find usages

### ISSUE THREAD

**Issue by vilterp** [durkiewicz/elm-plugin#22]
First of all, thanks for working on this! Super psyched to see it.

Go to definition works great, but I'm used to being able to `right click > find usages` on symbols in my editor and have the find pane pop up. It seems like with the PSI parsing in place, the foundation is there — what more is required for find usages to work?

Thanks!

**Comment by durkiewicz** [comment]
When I implemented finding usages it turned out that it indeed finds all usages but they are duplicated. So when you have, let's say, 1 usage of some symbol then IntelliJ displayed 3 usages, all in the same place. If you have some time to investigate it, you can see it on this branch:

https://github.com/durkiewicz/elm-plugin/tree/find-usages

**Comment by vilterp** [comment]
Weird. Thanks for the branch; I'll take a look

**Comment by klazuka** [comment]
@durkiewicz I dove into the debugger to try to figure this one out. The problem appears to be that IntelliJ is generating duplicate usages for the parent elements of the matched element. So it would seem to be a bug in the plugin's PSI tree or References.

# Example

simple example program:
<img width="212" alt="simple prog" src="https://cloud.githubusercontent.com/assets/84525/19221818/abf42722-8dff-11e6-98f2-9e8e8c5a6bb8.png">

after running 'find usages' on `text` in the body of `main`
<img width="432" alt="dupe usages" src="https://cloud.githubusercontent.com/assets/84525/19221819/b0d4b630-8dff-11e6-9470-ce40e1c43ec8.png">

I put a breakpoint on the constructor for `com.intellij.usageView.UsageInfo` and logged the element's file/module, type, and text content. Here is the console output:

```
file: Html, type: MODULE_DECLARATION, text: module Html exposing
  ( text, node, Html, Attribute
  , h1, h2, h3, h4, h5, h6
  , div, p, hr, pre, blockquote
  , span, a, code, em, strong, i, b, u, sub, sup, br
  , ol, ul, li, dl, dt, dd
  , img, iframe, canvas, svg, math
  , form, input, textarea, button, select, option
  , section, nav, article, aside, header, footer, address, main', body
  , figure, figcaption
  , table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th
  , fieldset, legend, label, datalist, optgroup, keygen, output, progress, meter
  , audio, video, source, track
  , embed, object, param
  , ins, del
  , small, cite, dfn, abbr, time, var, samp, kbd, s, q
  , mark, ruby, rt, rp, bdi, bdo, wbr
  , details, summary, menuitem, menu
  )
file: Html, type: LOWER_CASE_ID, text: text
file: Main, type: EXPOSING_CLAUSE, text: exposing (text)
file: Main, type: IMPORT_CLAUSE, text: import Html exposing (text)
file: Main, type: LOWER_CASE_PATH, text: text
file: Main, type: LIST_OF_OPERANDS, text: text "blah"
file: Main, type: EXPRESSION, text: text "blah"
file: Main, type: VALUE_DECLARATION, text: main =
    text "blah"
```

Note the duplicate usages in the Main module, but the Html module is fine. Not sure if crossing the module boundary is part of the problem or if that's a red-herring. But certainly the thing that looks suspicious is the nested duplication of usages (e.g. for `import Html exposing (text)`)

**Comment by klazuka** [comment]
my breakpoint log command looks like this: 
```
System.out.println("file: " + element.getContainingFile() + ", type: " + element.getNode().getElementType() + ", text: " + element.getText());
```

**Comment by klazuka** [comment]
It appears that the problem is due to how the References are implemented.

When searching for usages, IntelliJ uses `LowLevelSearchUtil.processTreeUp()` to work its way up from leaf nodes, building-up a list of `UsageInfo` objects from `PsiReference`s. It will stop walking up when it attempts to insert a duplicate UsageInfo or it reaches the root of the Psi tree.

The problem is that due to how `ElmPsiElement` is implemented, every element includes its children's references in its own list of references. So any parents of an element that contains a usage of the search term will also generate a separate usage object, thus the duplication in the results UI.

IntelliJ does have code to handle logical equality for these UsageInfo objects and de-duping when collecting them, but this does not help us because the usage *is* considered different (the child element referring to element X is considered different from the parent element who also refers to X). 

It seems like there are 2 solutions:
1. change how Element References work so that they no longer include the references of the children elements
2. try to arrange the references in such a way that we could leverage the existing de-dupe logic in IntelliJ.

The first option is guaranteed to work, but is probably a big architectural change. The second option would require few architectural changes, but would require digging into the exact details of how the de-dupe works, and even then, it may not even be possible.

@durkiewicz thoughts?

**Comment by durkiewicz** [comment]
Ad 1:
It is not a coincidence that references are implemented like that. My first attempt to implement them was to create them only on PSI leaves, but it didn't work. Navigation and other reference-based features just didn't work with references on leaves. Then I noticed that they do work when I create them for elements that are closer to the root in the PSI tree. So maybe, to deduplicate the usages we should do the opposite - prevent from returning the references on deeper elements. However, it is not clear to me which PSI element should actually return references (that's why all of them return them currently).

Ad 2:
I'm not aware how IntelliJ's de-dupe logic works so it's difficult for me to comment on that. Can you please link the code that does this job?

**Comment by klazuka** [comment]
I have commit ef5978e checked out in my IntelliJ CE source tree, and the line in question is line 389 in `FindUsagesManager`. It feeds the just-created `UsageInfo` object into a processor, which is an instance of `UniqueProcessor`. This adds the data to a set, which uses equality defined on UsageInfo to de-dupe.

<img width="952" alt="screen shot 2016-11-17 at 7 29 57 am" src="https://cloud.githubusercontent.com/assets/84525/20395434/c0e76cfa-ac97-11e6-9cd3-7c2f76f74152.png">

**Comment by klazuka** [comment]
I did some more looking into it earlier this morning. In order for it to be considered a dupe, the usage needs to span the same range in the text buffer *and* point to the same PsiElement in the tree.

As currently implemented, we satisfy the first condition (same text range), but fail the second. This is due to how `ElmReferenceBase.referenceInAncestor()` hoists the reference up into the ancestor. Shifting right by the diff is what keeps the text range in sync (which is good), but creating a new reference on the ancestor is what results in the same-element equality to fail.

I didn't get a chance to try it, but I wonder if the solution could be as simple as to avoid calling `referenceInAncestor`? Meaning that the ancestor would return the references of its children untouched. But maybe this is forbidden by the `PsiReference` interface? (I don't know enough about IntelliJ, and there is a real shortage of documentation)

**Comment by klazuka** [comment]
I did a quick hack to confirm things: make `referenceInAncestor()` just return `this` instead of "translating" the reference up into the ancestor. This definitely fixes the duplicated Find Usage results, but other things break (notably references in import clauses).

I also did a survey of how other language plugins do references. Of the languages I checked (Java, Python, Kotlin, JS and Bash), _none_ of them include references in the parent Psi elements. For simple stuff like identifiers, the leaf PsiElement would have no references, but it would be wrapped in a "ReferenceExpression" PsiElement, which does hold the reference.

So it would seem that by using the "nested" reference solution, we are outside of the mainstream, and will probably run into IntelliJ corner cases again and again.

**Comment by durkiewicz** [comment]
I've created a very simple language plugin that demonstrate the issue that I have with NOT having references in parent elements: https://github.com/durkiewicz/simple-language

If someone finds a way to resolve this issue in this simple plugin, then I promise to re-make all the references in Elm plugin. "Find usages" would become a trivial job after such refactoring.

**Comment by klazuka** [comment]
@durkiewicz Thanks for putting together the sample project demonstrating the problem. After some digging in and reading more about PsiReference, I think I have the solution: https://github.com/durkiewicz/simple-language/pull/1. 

Hopefully this won't be too hard of a change to make in the Elm plugin 😬

**Comment by dreadfulangel** [comment]
Hi @durkiewicz thanks for a great plugin, it's really great and everything is working except for this. Do you have any plans to continue to work on find usages?

Thank you!

**Comment by durkiewicz** [comment]
@dreadfulangel I do have such plans; I've already started the work, but I need to postpone all my open-source activities at least to November.

**Comment by klazuka** [comment]
@durkiewicz just giving you a heads-up: I've forked your repo and started re-writing the whole thing in Kotlin. My goals are:
- fix the reference system
- cleanup the parser by doing most of the whitespace/offside-rule logic in the lexer
- Kotlin instead of Java8
- manually created PsiElement subclasses

That last goal—manually creating the PsiElement subclasses—was born out of my frustration with how convoluted the core Psi tree domain becomes when GrammarKit generates the Psi clasess (due to the need to use mixins, method injection, and lots of inheritance). This may be a terrible idea, but I want to give it a try and see if the tradeoff is worth it.

Anyway, the reason I wanted to mention this was so that you don't spend time fixing the reference system strictly on my account. And I wanted to thank you for all of the work that you've put into this plugin. 🙏

**Comment by dreadfulangel** [comment]
@durkiewicz, anyway thank you for a great work! if you'll made this feature work that would be really amazing! @klazuka, would be happy to hear from you as well.

Thank you guys for a great work!

**Comment by klazuka** [comment]
I've released [my re-write](https://github.com/klazuka/intellij-elm) of the plugin, and it includes support for Find Usages. It's available now through the JetBrains plugin repository under the name "Elm". You will have to un-install the old plugin before installing the new one.

**Comment by durkiewicz** [comment]
@klazuka Congratulations! I'll probably remove this plugin soon.

**Comment by klazuka** [comment]
@durkiewicz I would prefer if you would hold-off on removing the plugin as there are a couple features that your plugin has which I haven't yet implemented. I don't want people to get stuck with something that is better in some places but worse in others. I hope to fill those gaps by early January.

**Comment by durkiewicz** [comment]
Thank you in your interest in the plugin. I'm sorry to say that this repository is no longer maintained due to lack of resources. If you need an Elm language support in IntelliJ - please consider using [this plugin](https://github.com/klazuka/intellij-elm) instead.
