### ISSUE TITLE
type checking

### ISSUE THREAD

**Issue by shmish111** [durkiewicz/elm-plugin#27]
Are you planning on type checking elm files? It would be nice if the elm compiler could be run, any errors underlined with squiggly red and the compiler error shown on hover. This is one feature that would make me switch from LightTable for sure.

**Comment by durkiewicz** [comment]
It's not possible to do it right with the current performance of `elm-make`. It takes several minutes to recompile after small change in a large Elm code base. It's not acceptable to wait that long in a graphical environment, is it?

**Comment by shmish111** [comment]
Well it works well in light table, no noticeable delay. Someone also said to me yesterday that it would be an elm game changer to have this.

**Comment by shmish111** [comment]
It seems like light table uses elm-make https://github.com/rundis/elm-light/blob/master/node/elm-client.js and when I've used it, as I said, it's totally acceptable.

**Comment by klazuka** [comment]
I don't have any experience running elm-make on any huge projects, but for small to medium size projects, it seems fast enough. But I guess it depends on whether you are talking about interactive, character-by-character invocation of elm-make or batch, on-save invocation.

The advantage of some kind of elm-make integration would be the ability to connect the compiler's error output directly to lines of code in the project source files. Right now you must context shift from IntelliJ to the terminal and back again, mapping line numbers and file names.

@durkiewicz do you have a better workflow? Perhaps running elm-make in a terminal *inside* IntelliJ?

**Comment by durkiewicz** [comment]
Actually if you guys need this feature then you can write a separate IntelliJ plugin just for `elm-make` integration. You won't need neither parser nor reference resolver to do it.

I've already stopped using Elm because of its compiler's performance so don't count on me.

**Comment by klazuka** [comment]
The problem with a separate plugin is that the out-of-the-box experience suffers, as now the user needs to know that they they need to get both the main plugin and the auxilliary plugin. 

Yes, this is similar to the situation with `elm-format` where you need to install an extra tool, but that one is unavoidable since it necessarily must live outside of the plugin.

> I've already stopped using Elm because of its compiler's performance so don't count on me.

@durkiewicz I had suspected as much since you weren't very active these last few months. I'm surprised that you're having compiler performance problems. How many lines-of-code is your project? 

And if you're not using Elm anymore, what are your plans for this plugin? I don't want to de-rail this conversation, so maybe we should discuss in a separate issue or just email me directly. Please let me know how you'd like me to help.
