### ISSUE TITLE
Darcula color scheme

### ISSUE THREAD

**Issue by durkiewicz** [durkiewicz/elm-plugin#43]
I've found the following comment on this site: https://plugins.jetbrains.com/plugin/8192

"Can you please test this plugin with the Darcula color scheme? The latest version renders all function names unreadable with having almost-black text over the dark background."

@klazuka Can you please check that?

**Comment by bgourlie** [comment]
I use Darcula and have not noticed any issues with font colors.

**Comment by durkiewicz** [comment]
OK, thanks for checking. I'll close it then.

**Comment by klazuka** [comment]
I reached out to the user via email. I suspect that the problem is due to customization. I bundle two color scheme files with the plugin, one based off of the light scheme and one for the dark scheme. Perhaps he's not getting the customization because he has already cloned the scheme under a different name?
