### ISSUE TITLE
Using elm-format for better src file formating

### ISSUE THREAD

**Issue by hipertracker** [durkiewicz/elm-plugin#9]
It could be great if Elm source file would be formatted by [elm-format](https://github.com/avh4/elm-format). [It works great for Sublime](https://github.com/deadfoxygrandpa/Elm.tmLanguage).

**Comment by durkiewicz** [comment]
It actually is possible. In order to do it you need to add `elm-format` as an external tool...
![screen shot 2016-05-19 at 08 19 55](https://cloud.githubusercontent.com/assets/2900637/15384534/aaa8530e-1d9b-11e6-91a6-391b46909544.png)

...and then attach any keyboard shortcut to it:

![screen shot 2016-05-19 at 08 22 52](https://cloud.githubusercontent.com/assets/2900637/15384539/b2d1e00e-1d9b-11e6-9d81-87cf739bbeda.png)

**Comment by durkiewicz** [comment]
I'm not going to have the elm-format built-in into the plugin because it is against IntelliJ's plugin development philosophy. The formatter should rather be implemented in plugin's code (not in an external tool) so that it work during typing, not after the code is already typed. If you would like to implement the formatter you can find a guide here: http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_formatting.html

**Comment by hipertracker** [comment]
That's cool. I have a problem with triggering elm-format after file saving. I could not find any special trigger for that so I created a new File Watcher for that. The problem is every time I save the file it trigger elm-format, which changes the source file in place (so far so good) but then it triggers elm-format over and over again, without end. Any hint how to fix this?

![image](https://cloud.githubusercontent.com/assets/649/15388482/0622a1a4-1daa-11e6-9b5f-a4b0159be93e.png)

**Comment by hipertracker** [comment]
The fix is simple.The working directory has to be $FileDir$ instead of $ProjectFileDir$.

**Comment by LucianU** [comment]
An issue I found with the solution above is that it breaks "Undo". @hipertracker, that isn't an issue for you?

**Comment by mordrax** [comment]
The settings above with `$FileDir$ or `$ProjectFileDir$` does not work for me, i'm still getting infinite looping of elm-format on Webstorm 2016.2.2

**Comment by shainegordon** [comment]
@mordrax Have you tried unchecking "Immediate file synchronization"?

**Comment by mordrax** [comment]
Yes, to no effect

**Comment by Ben52** [comment]
I was having an issue where the filename contained a space. Resolved by surrounding "$FilePath$".

**Comment by ianp** [comment]
Would you be willing to accept a PR that added `elm-format` support as a tool?

**Comment by durkiewicz** [comment]
@ianp I am not sure whether it is a good idea. What would users get? Would it be anyway different than the approach described above?

**Comment by ianp** [comment]
The main concrete benefit is that it works with _undo_ but it's also a better user experience.

Right now the story is: “go to this closed GitHub issue and follow the instructions there, but be careful to read all of them or it won't work with some files due to spaces in the path. Oh yeah, it'll break undo as well.” I'm proposing: “Go to this tool in settings, select the checkbox.”

One thing that I maybe would alter from my current version: instead of calling the tool “Elm Format” I'd label it “Elm Tools” as I'd like to add an option to also run saved files through the Elm compiler to take advantage of it's error highlighting.

**Comment by durkiewicz** [comment]
@ianp I'm not enthusiastic about a perspective of maintaining such tools. I suggest you

- either create a separate "Elm Tools" plugin strictly for integration with command-line tools like elm-format or elm-make,
- or fork my repo, add this functionality and submit a second Elm plugin to JetBrains repo.
